# -*- coding: utf-8 -*-
"""dental xray disease detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qFbE5scU4KbNDvyyic1w15MuhbJskGt1
"""

from PIL import Image, ImageDraw, ImageFont
from ultralytics import YOLO
from PIL import Image, ImageDraw
import matplotlib.pyplot as plt

model_path = "/kaggle/input/dental-disease-panoramic-detection-dataset/best.pt"
model = YOLO(model_path)

img_path = "/kaggle/input/dental-disease-panoramic-detection-dataset/COCO/COCO/train/000dc27f-NAJIB_MARDANLOO_MASUME_2020-07-12185357_jpg.rf.76cabac5ba504297e98502d2731728d5.jpg"
img = Image.open(img_path)


ROW_HEIGHT = 45
LEGEND_WIDTH = 450
FONT_SIZE = 26

CLASS_NAMES = [
    "Caries", "Crown", "Filling", "Implant", "Malaligned", "Mandibular Canal", "Missing teeth",
    "Periapical lesion", "Retained root", "Root Canal Treatment", "Root Piece", "Impacted tooth",
    "Maxillary sinus", "Bone Loss", "Fractured teeth", "Permanent Teeth", "Supra Eruption", "TAD",
    "Abutment", "Attrition", "Bone defect", "Gingival former", "Metal band", "Orthodontic brackets",
    "Permanent retainer", "Post-core", "Plating", "Wire", "Cyst", "Root resorption", "Primary teeth"
]

PALETTE = [
    (220, 20, 60), (119, 11, 32), (0, 0, 142), (0, 0, 230), (106, 0, 228),
    (0, 60, 100), (0, 80, 100), (0, 0, 70), (0, 0, 192), (250, 170, 30),
    (100, 170, 30), (220, 220, 0), (175, 116, 175), (250, 0, 30),
    (30, 144, 255), (0, 191, 255), (135, 206, 250), (70, 130, 180), (123, 104, 238),
    (72, 61, 139), (138, 43, 226), (148, 0, 211), (186, 85, 211), (255, 20, 147),
    (255, 105, 180), (255, 160, 122), (255, 69, 0), (255, 99, 71), (218, 112, 214),
    (238, 130, 238), (255, 222, 173)
]


results = model.predict(img)

annotated_img = img.copy()
draw = ImageDraw.Draw(annotated_img)

for detection, class_id in zip(results[0].boxes, results[0].boxes.cls):
    x1, y1, x2, y2 = detection.xyxy[0].tolist()
    class_id = int(class_id.item())

    color = PALETTE[class_id % len(PALETTE)]

    draw.rectangle(
        [(x1, y1), (x2, y2)],
        outline=color,
        width=3
    )

try:
    font = ImageFont.load_default(size=FONT_SIZE)
except TypeError:
    font = ImageFont.load_default()

canvas = Image.new(
    "RGB",
    (img.width + LEGEND_WIDTH, img.height),
    (255, 255, 255)
)

canvas.paste(annotated_img, (0, 0))

legend_height = max(len(CLASS_NAMES) * ROW_HEIGHT, img.height)
legend = Image.new(
    "RGB",
    (LEGEND_WIDTH, legend_height),
    (255, 255, 255)
)

draw_legend = ImageDraw.Draw(legend)

for i, (color, name) in enumerate(zip(PALETTE, CLASS_NAMES)):
    y = i * ROW_HEIGHT

    draw_legend.rectangle(
        [15, y + 5, 55, y + 35],
        fill=color
    )

    draw_legend.text(
        (75, y + 5),
        name,
        fill=(0, 0, 0),
        font=font
    )

canvas.paste(
    legend,
    (img.width, 0)
)

plt.figure(figsize=(20, 12))
plt.imshow(canvas)
plt.axis("off")
plt.show()